# @package _global_
defaults:
- override /base: classification
- override /data: mmpretrain
- override /model: mmpretrain
data:
  subsets:
    train:
      batch_size: 128
      transforms:
      - backend_args: null
        type: LoadImageFromFile
      - backend: pillow
        scale: 224
        type: RandomResizedCrop
      - direction: horizontal
        prob: 0.5
        type: RandomFlip
      - hparams:
          pad_val:
          - 104
          - 116
          - 124
        policies: imagenet
        type: AutoAugment
      - erase_prob: 0.2
        fill_color:
        - 103.53
        - 116.28
        - 123.675
        fill_std:
        - 57.375
        - 57.12
        - 58.395
        max_area_ratio: 0.3333333333333333
        min_area_ratio: 0.02
        mode: rand
        type: RandomErasing
      - type: PackInputs
    val:
      batch_size: 128
      transforms:
      - type: LoadImageFromFile
      - backend: pillow
        edge: short
        scale: 256
        type: ResizeEdge
      - crop_size: 224
        type: CenterCrop
      - type: PackInputs
model:
  otx_model:
    config:
      backbone:
        arch: large
        type: MobileNetV3
      head:
        act_cfg:
          type: HSwish
        dropout_rate: 0.2
        in_channels: 960
        init_cfg:
          bias: 0.0
          layer: Linear
          mean: 0.0
          std: 0.01
          type: Normal
        loss:
          loss_weight: 1.0
          type: CrossEntropyLoss
        mid_channels:
        - 1280
        num_classes: 1000
        topk:
        - 1
        - 5
        type: StackedLinearClsHead
      neck:
        type: GlobalAveragePooling
      type: ImageClassifier
