# @package _global_
defaults:
- override /base: classification
- override /data: mmpretrain
- override /model: mmpretrain
data:
  subsets:
    train:
      batch_size: 128
      transforms:
      - type: LoadImageFromFile
      - backend: pillow
        scale: 224
        type: RandomResizedCrop
      - direction: horizontal
        prob: 0.5
        type: RandomFlip
      - hparams:
          pad_val:
          - 104
          - 116
          - 124
        policies: imagenet
        type: AutoAugment
      - erase_prob: 0.2
        fill_color:
        - 103.53
        - 116.28
        - 123.675
        fill_std:
        - 57.375
        - 57.12
        - 58.395
        max_area_ratio: 0.3333333333333333
        min_area_ratio: 0.02
        mode: rand
        type: RandomErasing
      - type: PackInputs
    val:
      batch_size: 128
      transforms:
      - type: LoadImageFromFile
      - backend: pillow
        edge: short
        scale: 256
        type: ResizeEdge
      - crop_size: 224
        type: CenterCrop
      - type: PackInputs
model:
  otx_model:
    config:
      backbone:
        arch: deit-small
        type: VisionTransformer
        img_size: 224
        patch_size: 16
      head:
        loss:
          loss_weight: 1.0
          type: CrossEntropyLoss
        in_channels: 384
        num_classes: 1000
        type: VisionTransformerClsHead
      data_preprocessor:
        mean:
          - 123.675
          - 116.28
          - 103.53
        num_classes: 1000
        std:
          - 58.395
          - 57.12
          - 57.375
        to_rgb: True
        type: ClsDataPreprocessor
      init_cfg:
        - std: 0.2
          layer: Linear
          type: TruncNormal
        - bias: 0.
          val: 1.
          layer: LayerNorm
          type: Constant
      type: ImageClassifier