# Description.
model_template_id: ClassIncremental_Semantic_Segmentation_Lite-HRNet-18_OCR
name: Lite-HRNet-18 OCR-ClsIncr
task_type: SEGMENTATION
task_family: VISION
instantiation: "CLASS"
summary: Class-Incremental Semantic Segmentation for Lite-HRNet-18 OCR
application: ~

# Algo backend.
framework: MPA v1.1.0

# Task implementations.
entrypoints:
  base: mpa_tasks.apis.segmentation.SegmentationTrainTask
  openvino: segmentation_tasks.apis.segmentation.OpenVINOSegmentationTask

# Capabilities.
capabilities: []

# Hyperparameters.
hyper_parameters:
  base_path: ../configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 4
      learning_rate:
        default_value: 0.001
      learning_rate_fixed_iters:
        default_value: 0
      learning_rate_warmup_iters:
        default_value: 80
      num_iters:
        default_value: 180
    algo_backend:
      train_type:
        default_value: Incremental

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 3.45
size: 4.5
